title: Windows Defender Threat Protection Settings Disabled via GUI
id: 87c21d4e-e312-4f0b-ab86-f9b8e60dd68e
status: experimental
description: Detects when a user disables Defender settings via GUI.  This can be used by adversaries to impair defenses.
references:
    - http://www.huntress.com/blog/its-not-safe-to-pay-safepay
    - https://www.huntress.com/blog/lolbin-to-inc-ransomware
author: Matt Anderson (Huntress)
date: 2024-11-01
tags:
    - attack.defense-evasion
    - attack.t1562
logsource:
    category: process_creation
    product: windows
detection:
    selection_img:
        - Image|endswith: '\SystemSettingsAdminFlows.exe'
        - OriginalFileName: 'SystemSettingsAdminFlows.EXE'
    selection_parent_img:
        - ParentImage|endswith: '\SystemSettings.exe'
    selection_cli:
        CommandLine|contains:
            - 'Defender DisableEnhancedNotifications 1'
            - 'Defender SubmitSamplesConsent 0'
            - 'Defender SpynetReporting 0'
            - 'Defender RTP 1'
    condition: all of selection_*
falsepositives:
    - May be turned off by a user or admin for legitimate purposes.
level: medium